path:
  BP_dir: /kaggle/input/deepca-preprocessed-dataset/data/CCTA_BP
  label_dir: /kaggle/input/deepca-preprocessed-dataset/data/split_two
  output_dir: /kaggle/working
  checkpoint_dir: /kaggle/input/deepca-training-18/outputs_results/checkpoints
  model_dir: /kaggle/working/DeepCA

hyperparameters:
  learning_rate: 0.0001
  extra_epochs: 10
  lambda_term: 10
  batch_size: 1
  betas:
    - 0.5
    - 0.9